/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.antonov.tomographysoftwarediploma.viewSwing;

import com.antonov.tomographysoftwarediploma.impl.DensityAnalizator;
import com.antonov.tomographysoftwarediploma.impl.imageprocessing.Utils;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Antonov
 */
public class DensityAnalizatorPane extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    BufferedImage reconstructImage;
    BufferedImage scaleReconstructImage;

    public DensityAnalizatorPane() {
        initComponents();
    }

    public DensityAnalizatorPane(BufferedImage image) {
        this.reconstructImage = image;
        initComponents();
        initImageForAnylize();
        initGraphArea();
    }

    private void initImageForAnylize() {
        scaleReconstructImage = DensityAnalizator.scaleImage(reconstructImage, 300, 300, Color.white);
        BufferedImage scaleReconstructImageCursor = DensityAnalizator.generateCursorOnImage(scaleReconstructImage, 0);

        ImageIcon icon = new ImageIcon(scaleReconstructImageCursor);
        labelImageDensityViewer.setIcon(icon);
    }

    private void initGraphArea() {

        double[][] densitySourseArray = Utils.getDoubleRevertedArrayPixelsFromBufImg(reconstructImage);
        int initialLineSlise = densitySourseArray.length / 2;
        densitySlider.setMaximum(densitySourseArray.length - 1);
        densitySlider.setMajorTickSpacing(densitySourseArray.length / 10);
        densitySlider.setPaintLabels(true);
        densitySlider.setPaintTicks(true);

        densityGraphPane.setLayout(new java.awt.BorderLayout());
        densityGraphPane.add(DensityAnalizator.generateDensityGraph(reconstructImage, initialLineSlise), BorderLayout.CENTER);
        densityGraphPane.validate();

        densitySlider.addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
                int lineSlise = densitySlider.getValue();
                int maxSlider = densitySlider.getMaximum();
                int scaleLineSlise = (int) ((300 * lineSlise) / maxSlider);
                scaleReconstructImage = DensityAnalizator.scaleImage(reconstructImage, 300, 300, Color.white);
                BufferedImage scaleReconstructImageLine = DensityAnalizator.generateCursorOnImage(scaleReconstructImage, scaleLineSlise);
                ImageIcon icon = new ImageIcon(scaleReconstructImageLine);
                labelImageDensityViewer.setIcon(null);
                labelImageDensityViewer.setIcon(icon);
                densityGraphPane.removeAll();
                densityGraphPane.add(DensityAnalizator.generateDensityGraph(reconstructImage, lineSlise), BorderLayout.CENTER);
                densityGraphPane.validate();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        labelImageDensityViewer = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        densityGraphPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        densitySlider = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 600));
        setType(java.awt.Window.Type.UTILITY);

        jSplitPane1.setResizeWeight(0.4);
        jSplitPane1.setToolTipText("");

        jPanel3.setLayout(new java.awt.GridBagLayout());

        labelImageDensityViewer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImageDensityViewer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelImageDensityViewer)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelImageDensityViewer)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jPanel4, gridBagConstraints);

        jSplitPane1.setLeftComponent(jPanel3);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        densityGraphPane.setOpaque(false);
        densityGraphPane.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout densityGraphPaneLayout = new javax.swing.GroupLayout(densityGraphPane);
        densityGraphPane.setLayout(densityGraphPaneLayout);
        densityGraphPaneLayout.setHorizontalGroup(
            densityGraphPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(densityGraphPaneLayout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel1))
        );
        densityGraphPaneLayout.setVerticalGroup(
            densityGraphPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(densityGraphPaneLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(densityGraphPane, gridBagConstraints);

        densitySlider.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        densitySlider.setValue(0);
        densitySlider.setFocusable(false);
        densitySlider.setRequestFocusEnabled(false);
        densitySlider.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(densitySlider, gridBagConstraints);

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DensityAnalizatorPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DensityAnalizatorPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DensityAnalizatorPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DensityAnalizatorPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DensityAnalizatorPane(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel densityGraphPane;
    private javax.swing.JSlider densitySlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labelImageDensityViewer;
    // End of variables declaration//GEN-END:variables
}
